### ISSUE TITLE
Duplicate Keys within a resource are overwritten by last item.

### ISSUE THREAD

**Issue by rkive** [chrisfjones/coffin#10]
My example template and output:  https://gist.github.com/3453821

I'm unsure the best way to approach the scenario above. I'm attempting to create SecurityGroups that have multiple CIDR or EC2SecurityGroupName entries. Coffin will only create a single item of each type.

**Comment by chrisfjones** [comment]
Coffee-scripts JSON simplification kind of breaks down here so you'll need some additional syntax hints so the correct structure is created:

``` javascript
DBSecurityGroupIngress: [
  { CIDRIP: "10.10.10.10/32" }
  { CIDRIP: "10.11.11.11/32" }
  { EC2SecurityGroupName: "sampleGroup1" }
  { EC2SecurityGroupName: "sampleGroup2" }
]
```
